### ISSUE TITLE
Does not run in macOs Catalina

### ISSUE THREAD

**Issue by lucas-marciano** [julianxhokaxhiu/iPoPS#2]

**Comment by julianxhokaxhiu** [comment]
It's being a long time since I didn't compile it. Feel free to come up with a PR, or I'll try to fix it as soon as I'll have some time.

**Comment by ViiMorales** [comment]
should work with #3

**Comment by julianxhokaxhiu** [comment]
Thanks! I'll check it out and let you know soon :)

**Comment by julianxhokaxhiu** [comment]
PR Merged. Thank you!

**Comment by julianxhokaxhiu** [comment]
Just pushed a new release out. It is now built using AppVeyor CI. Feel free to try it and let me know! Cheers :)
