### ISSUE TITLE
Black Screen after converting bin to eboot

### ISSUE THREAD

**Issue by bytewired** [julianxhokaxhiu/iPoPS#4]
Hi, thank you for your work. But after converting `bin` file when I start game, I'm getting a black screen on my psp, after intro screen. How can I get to know what went wrong or maybe it's known issue?

**Comment by julianxhokaxhiu** [comment]
Hi @Ne1c Thank you!

Are you sure the game you're trying to run is compatible with PoPS? May be an emulator issue on the PSP rather than a conversion issue. To make sure of that, just try the resulting PBP on RetroArch :)

Let me know how it goes.
